FROM public.ecr.aws/docker/library/maven:3-amazoncorretto-25-al2023 AS builder

COPY ./pom.xml ./pom.xml
COPY src ./src/

RUN mvn clean package -DskipTests -ntp && mv target/store-spring-1.0.0-exec.jar store-spring.jar

FROM public.ecr.aws/docker/library/amazoncorretto:25-al2023 AS trainer

COPY --from=builder store-spring.jar store-spring.jar

# Generate CDS archive (Spring Boot exits after context refresh)
RUN java -Dspring.context.exit=onRefresh \
    -XX:ArchiveClassesAtExit=/app.jsa \
    -Dspring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration \
    -jar store-spring.jar || true

FROM public.ecr.aws/docker/library/amazoncorretto:25-al2023

RUN yum install -y shadow-utils

COPY --from=builder store-spring.jar store-spring.jar
COPY --from=trainer /app.jsa /app.jsa

RUN groupadd --system spring -g 1000
RUN adduser spring -u 1000 -g 1000

USER 1000:1000
EXPOSE 8080

ENTRYPOINT ["java", "-XX:+UseCompactObjectHeaders", "-XX:SharedArchiveFile=/app.jsa", "-jar", "-Dserver.port=8080", "/store-spring.jar"]
