#!/usr/bin/env bash

# Generated by infra/scripts/ws-test/generate.mjs. Do not edit.

set -Eeuo pipefail
WS_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${WS_SCRIPT_DIR}/runtime.sh"
ws_begin_run 'Java performance optimization' "${WS_SCRIPT_DIR}/reports/java-performance" 5 "$@"
ws_set_executable_total 32
ws_set_default_timeout 600
ws_source_environment '/etc/profile.d/workshop.sh'

ws_begin_page 'Meet the application' 50 'architecture/index.en.md'

ws_run_block 1 'Test the application' 'Test the application' 39 47 'bash' '' <<'WS_TEST_BLOCK_50_1'
kubectl -n unicorn-store-spring get deployment,pod
SVC_URL=http://$(kubectl -n unicorn-store-spring get ingress unicorn-store-spring -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
curl --location $SVC_URL; echo
curl --location --request POST $SVC_URL'/unicorns' --header 'Content-Type: application/json' --data-raw '{
    "name": "'"Something-$(date +%s)"'",
    "age": "20",
    "type": "Animal",
    "size": "Very big"
}' | jq
WS_TEST_BLOCK_50_1

ws_skip_block 2 'Test the application' 'Sample output:' 53 60 'json' '' 'copy action disabled'

ws_run_block 3 'Start the load' 'Start the load' 68 68 'bash' '' <<'WS_TEST_BLOCK_50_3'
nohup bash -c 'while true; do ~/environment/unicorn-store-spring/scripts/load.sh 600 50; done' > ~/environment/load.log 2>&1 &
WS_TEST_BLOCK_50_3

ws_run_block 4 'Open Grafana' 'Grafana is an open-source dashboard tool. Here it shows the application'"'"'s metrics from Prometheus and its CPU profiles from Pyroscope.' 80 84 'bash' '' <<'WS_TEST_BLOCK_50_4'
GRAFANA_URL=$(kubectl -n monitoring get svc grafana -o jsonpath="{.status.loadBalancer.ingress[0].hostname}")
GRAFANA_PASSWORD=$(kubectl -n monitoring get secret grafana-admin -o jsonpath="{.data.password}" | base64 --decode)
echo "URL:      http://${GRAFANA_URL}"
echo "Username: admin"
echo "Password: ${GRAFANA_PASSWORD}"
WS_TEST_BLOCK_50_4

ws_end_page

ws_begin_page 'Measure the baseline' 100 'baseline/index.en.md'

ws_run_block 1 'Attach the profiler' 'The change is one label on the pod template. A cluster policy injects a profiler sidecar into any pod that carries it, and apply rolls the pod:' 19 27 'bash' '' <<'WS_TEST_BLOCK_100_1'
yq -i '.spec.template.metadata.labels."perf-profile/sidecar" = "true"' ~/environment/unicorn-store-spring/k8s/deployment.yaml
kubectl -n unicorn-store-spring apply -f ~/environment/unicorn-store-spring/k8s/deployment.yaml
kubectl -n unicorn-store-spring rollout status deploy/unicorn-store-spring --timeout=300s

# two containers now: the application and the sidecar
kubectl -n unicorn-store-spring get pod -l app=unicorn-store-spring -o jsonpath='{.items[0].spec.containers[*].name}'; echo

git -C ~/environment/unicorn-store-spring add -A \
  && git -C ~/environment/unicorn-store-spring commit -q -m "baseline: profiler attached"
WS_TEST_BLOCK_100_1

ws_run_block 2 'Connect the sensor' 'The sensor runs in the monitoring namespace. Forward it to the IDE in the background; the loop reconnects if the pod moves:' 37 38 'bash' '' <<'WS_TEST_BLOCK_100_2'
nohup bash -c 'while true; do kubectl -n monitoring port-forward svc/perf-sensor 8090:8080; sleep 2; done' > ~/environment/port-forward.log 2>&1 &
sleep 3; curl -sf localhost:8090/actuator/health && echo
WS_TEST_BLOCK_100_2

ws_skip_block 3 'Start Claude Code' 'Open a second terminal, the Claude terminal, and start Claude Code there, from ~/environment, where the session'"'"'s Claude Code configuration lives:' 50 50 'bash' '' 'interactive terminal UI'

ws_run_block 4 'Start Claude Code' 'With -p, Claude Code prints the answer and exits; later calls with -c continue the same session:' 70 70 'bash' 'non-interactive' <<'WS_TEST_BLOCK_100_4'
cd ~/environment && claude -p "List the MCP tools you can see from perf-sensor and eks-mcp, names only."
WS_TEST_BLOCK_100_4

ws_run_block 5 'Ask for the baseline' 'In the Shell terminal:' 97 97 'bash' 'non-interactive' <<'WS_TEST_BLOCK_100_5'
cd ~/environment && claude -c -p "How is unicorn-store-spring doing against best practices?"
WS_TEST_BLOCK_100_5

ws_run_block 6 'What is behind the question' '- unicorn-store-spring/CLAUDE.md: how the repository builds and deploys, for the agent' 124 126 'bash' '' <<'WS_TEST_BLOCK_100_6'
cat ~/environment/.mcp.json
ls ~/environment/.claude/skills/*/ ~/environment/.claude/skills/*/references/
cat ~/environment/.claude/skills/java-on-eks-optimization/references/sizing-policy.yaml
WS_TEST_BLOCK_100_6

ws_skip_block 7 'The baseline score' 'The baseline score' 135 151 'text' '' 'copy action disabled'

ws_end_page

ws_begin_page 'Right-size memory' 200 'right-size-memory/index.en.md'

ws_run_block 1 'Right-size memory' 'In the Shell terminal:' 21 21 'bash' 'non-interactive' <<'WS_TEST_BLOCK_200_1'
cd ~/environment && claude -c -p "How can I reduce memory consumption of unicorn-store-spring?"
WS_TEST_BLOCK_200_1

ws_skip_block 2 'Right-size memory' 'Claude measures the pod under the running load, computes the new sizes with a fixed policy, and edits one file. It edits and stops; nothing is deployed.' 33 55 'text' '' 'copy action disabled'

ws_run_block 3 'Roll out' 'In the Shell terminal. The pod template changed, so apply rolls out a new pod:' 66 66 'bash' '' <<'WS_TEST_BLOCK_200_3'
kubectl -n unicorn-store-spring apply -f ~/environment/unicorn-store-spring/k8s/deployment.yaml
WS_TEST_BLOCK_200_3

ws_skip_block 4 'What changed' 'Claude changed one file, k8s/deployment.yaml, in two blocks. The sizes come from sizeMemory with a fixed policy: limits = max(1.4 × peak, 1.5 × floor) rounded up to 128 MiB, and requests = limits.' 94 103 'yaml' '' 'copy action disabled'

ws_run_block 5 'Verify' 'Verify' 119 127 'bash' '' <<'WS_TEST_BLOCK_200_5'
kubectl -n unicorn-store-spring rollout status deploy/unicorn-store-spring --timeout=300s

# did the heap follow the container? 75 % / 50 % of the limit, SerialGC
kubectl -n unicorn-store-spring exec deploy/unicorn-store-spring -c unicorn-store-spring -- \
  sh -c 'JAVA_TOOL_OPTIONS= jcmd $(jcmd -l | grep -v JCmd | cut -d" " -f1) VM.flags' \
  | tr ' ' '\n' | grep -E 'MaxHeapSize|InitialHeapSize|UseSerialGC'

git -C ~/environment/unicorn-store-spring add -A \
  && git -C ~/environment/unicorn-store-spring commit -q -m "right-size memory"
WS_TEST_BLOCK_200_5

ws_skip_block 6 'Verify' 'Verify' 134 140 'text' '' 'copy action disabled'

ws_run_block 7 'Check against best practices' 'In the Shell terminal:' 167 167 'bash' 'non-interactive' <<'WS_TEST_BLOCK_200_7'
cd ~/environment && claude -c -p "How is unicorn-store-spring doing against best practices?"
WS_TEST_BLOCK_200_7

ws_skip_block 8 'Check against best practices' 'Check against best practices' 177 196 'text' '' 'copy action disabled'

ws_end_page

ws_begin_page 'Boost startup CPU' 300 'boost-startup-cpu/index.en.md'

ws_run_block 1 'Boost startup CPU' 'In the Shell terminal:' 21 21 'bash' 'non-interactive' <<'WS_TEST_BLOCK_300_1'
cd ~/environment && claude -c -p "How can unicorn-store-spring start faster without changing the image?"
WS_TEST_BLOCK_300_1

ws_skip_block 2 'Boost startup CPU' 'Claude measures the pod, computes the steady-state CPU request, and edits two files. It edits and stops; nothing is deployed.' 31 55 'text' '' 'copy action disabled'

ws_run_block 3 'Roll out' 'In the Shell terminal:' 66 67 'bash' '' <<'WS_TEST_BLOCK_300_3'
kubectl -n unicorn-store-spring apply -f ~/environment/unicorn-store-spring/k8s/startup-cpu-boost.yaml
kubectl -n unicorn-store-spring apply -f ~/environment/unicorn-store-spring/k8s/deployment.yaml
WS_TEST_BLOCK_300_3

ws_skip_block 4 'What changed' 'Claude changed two files. A new StartupCPUBoost resource doubles CPU until the pod is Ready; the Deployment lowers the steady request and pins the JVM'"'"'s processor count.' 97 118 'yaml' '' 'copy action disabled'

ws_skip_block 5 'What changed' '- Lines 19–22: the controller removes the boost, in place, the moment the pod reports Ready' 127 136 'yaml' '' 'copy action disabled'

ws_run_block 6 'Verify' 'Verify' 146 159 'bash' '' <<'WS_TEST_BLOCK_300_6'
kubectl -n unicorn-store-spring rollout status deploy/unicorn-store-spring --timeout=300s

# startup line: about 7 s, was about 14
curl -s localhost:8090/api/v1/startupLog/unicorn-store-spring | jq -r .line

# the pod's actual resources once the controller has resized it down: request as computed, limit 1
sleep 30; kubectl -n unicorn-store-spring get pod -l app=unicorn-store-spring \
  -o jsonpath='{.items[0].spec.containers[0].resources}'; echo

# what the JVM saw: effectiveCpuCount 1 (pinned), cpuQuotaCores 2.0 (boosted at boot)
curl -s localhost:8090/api/v1/measure/unicorn-store-spring | jq '.jfr.container'

git -C ~/environment/unicorn-store-spring add -A \
  && git -C ~/environment/unicorn-store-spring commit -q -m "startup cpu boost + cpu request"
WS_TEST_BLOCK_300_6

ws_skip_block 7 'Verify' 'Verify' 164 174 'text' '' 'copy action disabled'

ws_run_block 8 'Check against best practices (optional)' 'In the Shell terminal:' 201 201 'bash' 'non-interactive' <<'WS_TEST_BLOCK_300_8'
cd ~/environment && claude -c -p "How is unicorn-store-spring doing against best practices?"
WS_TEST_BLOCK_300_8

ws_skip_block 9 'Check against best practices (optional)' 'Check against best practices (optional)' 209 224 'text' '' 'copy action disabled'

ws_end_page

ws_begin_page 'Cache startup at build time' 400 'cache-startup/index.en.md'

ws_run_block 1 'Cache startup at build time' 'In the Shell terminal:' 23 23 'bash' 'non-interactive' <<'WS_TEST_BLOCK_400_1'
cd ~/environment && claude -c -p "How can unicorn-store-spring start faster without changing the application?"
WS_TEST_BLOCK_400_1

ws_skip_block 2 'Cache startup at build time' 'Claude measures the running pod, reads pom.xml, and writes one file. It edits and stops; nothing is built or deployed.' 33 58 'text' '' 'copy action disabled'

ws_run_block 3 'Build and roll out' 'In the Shell terminal:' 69 75 'bash' '' 1200 <<'WS_TEST_BLOCK_400_3'
# ≈ 1 min on the warm cache, ≈ 3 min cold; two training runs; pushes :aot
~/environment/unicorn-store-spring/scripts/build.sh aot Dockerfile.aot

# point the Deployment at the :aot tag and roll it out
yq -i '.spec.template.spec.containers[0].image |= sub(":[^:]+$"; ":aot")' \
  ~/environment/unicorn-store-spring/k8s/deployment.yaml
kubectl -n unicorn-store-spring apply -f ~/environment/unicorn-store-spring/k8s/deployment.yaml
WS_TEST_BLOCK_400_3

ws_skip_block 4 'What changed' 'The copy in your repository carries the explanatory comments Claude kept from its reference. They are omitted here.' 180 236 'dockerfile' '' 'copy action disabled'

ws_run_block 5 'Verify' 'Verify' 253 259 'bash' '' <<'WS_TEST_BLOCK_400_5'
kubectl -n unicorn-store-spring rollout status deploy/unicorn-store-spring --timeout=300s

# startup line, about 3 s
curl -s localhost:8090/api/v1/startupLog/unicorn-store-spring | jq -r .line

git -C ~/environment/unicorn-store-spring add -A \
  && git -C ~/environment/unicorn-store-spring commit -q -m "aot cache"
WS_TEST_BLOCK_400_5

ws_skip_block 6 'Verify' 'Verify' 264 273 'text' '' 'copy action disabled'

ws_run_block 7 'Check against best practices (optional)' 'In the Shell terminal:' 300 300 'bash' 'non-interactive' <<'WS_TEST_BLOCK_400_7'
cd ~/environment && claude -c -p "How is unicorn-store-spring doing against best practices?"
WS_TEST_BLOCK_400_7

ws_skip_block 8 'Check against best practices (optional)' 'Check against best practices (optional)' 308 326 'text' '' 'copy action disabled'

ws_end_page

ws_begin_page 'Restore instead of start' 500 'restore-not-start/index.en.md'

ws_run_block 1 'Restore instead of start' 'In the Shell terminal:' 21 21 'bash' 'non-interactive' <<'WS_TEST_BLOCK_500_1'
cd ~/environment && claude -c -p "How can unicorn-store-spring start in under a second?"
WS_TEST_BLOCK_500_1

ws_skip_block 2 'Restore instead of start' 'Claude measures the running pod, reads the source, and edits four files. It edits and stops; nothing is built or deployed.' 31 60 'text' '' 'copy action disabled'

ws_run_block 3 'Build and roll out' 'In the Shell terminal. The build starts the application inside Docker, warms it up, checkpoints, and pushes the :crac tag:' 71 77 'bash' '' 1200 <<'WS_TEST_BLOCK_500_3'
# ≈ 3 min: builds, starts, warms up, checkpoints; pushes :crac
~/environment/unicorn-store-spring/scripts/build.sh crac Dockerfile.crac

# point the Deployment at the :crac tag and roll it out
yq -i '.spec.template.spec.containers[0].image |= sub(":[^:]+$"; ":crac")' \
  ~/environment/unicorn-store-spring/k8s/deployment.yaml
kubectl -n unicorn-store-spring apply -f ~/environment/unicorn-store-spring/k8s/deployment.yaml
WS_TEST_BLOCK_500_3

ws_skip_block 4 'What changed' '- k8s/deployment.yaml: JAVATOOLOPTIONS removed, because a restored JVM ignores MaxRAMPercentage and GC flags there crash the restore. The image tag changes to :crac in the build block above' 114 158 'dockerfile' '' 'copy action disabled'

ws_skip_block 5 'What changed' '- Line 45: -XX:CRaCRestoreFrom restores instead of starting. There are no GC or heap flags here; they came with the checkpoint' 178 209 'java' '' 'copy action disabled'

ws_run_block 6 'Verify' 'Verify' 221 232 'bash' '' <<'WS_TEST_BLOCK_500_6'
kubectl -n unicorn-store-spring rollout status deploy/unicorn-store-spring --timeout=300s

# startup line: "restored", well under a second
curl -s localhost:8090/api/v1/startupLog/unicorn-store-spring | jq -r .line

# heap flags came from the checkpoint: 75 % / 50 % of the limit, SerialGC
kubectl -n unicorn-store-spring exec deploy/unicorn-store-spring -c unicorn-store-spring -- \
  sh -c 'JAVA_TOOL_OPTIONS= jcmd $(jcmd -l | grep -v JCmd | cut -d" " -f1) VM.flags' \
  | tr ' ' '\n' | grep -E 'MaxHeapSize|InitialHeapSize|UseSerialGC'

git -C ~/environment/unicorn-store-spring add -A \
  && git -C ~/environment/unicorn-store-spring commit -q -m "crac"
WS_TEST_BLOCK_500_6

ws_skip_block 7 'Verify' 'Verify' 237 250 'text' '' 'copy action disabled'

ws_run_block 8 'Check against best practices' 'In the Shell terminal:' 277 277 'bash' 'non-interactive' <<'WS_TEST_BLOCK_500_8'
cd ~/environment && claude -c -p "How is unicorn-store-spring doing against best practices?"
WS_TEST_BLOCK_500_8

ws_skip_block 9 'Check against best practices' 'Check against best practices' 285 306 'text' '' 'copy action disabled'

ws_end_page

ws_begin_page 'Unblock the request path' 600 'unblock-requests/index.en.md'

ws_run_block 1 'Unblock the request path' 'In the Shell terminal:' 21 21 'bash' 'non-interactive' <<'WS_TEST_BLOCK_600_1'
cd ~/environment && claude -c -p "Why do some writes to unicorn-store-spring take seconds under load and how do I fix it?"
WS_TEST_BLOCK_600_1

ws_skip_block 2 'Unblock the request path' 'Claude takes thread dumps of the pod under the running load, finds the frame, reads the source, and edits a few files. It edits and stops; nothing is built or deployed.' 31 59 'text' '' 'copy action disabled'

ws_run_block 3 'Build and roll out' 'In the Shell terminal. The code changed, so you rebuild the current image. It is the CRaC image, so the build retakes the checkpoint with the fixed code:' 70 74 'bash' '' 1200 <<'WS_TEST_BLOCK_600_3'
# the code changed: rebuild the current image (≈ 2 min)
~/environment/unicorn-store-spring/scripts/build.sh crac Dockerfile.crac

# same tag, new digest: restart to pull it
kubectl -n unicorn-store-spring rollout restart deploy/unicorn-store-spring
WS_TEST_BLOCK_600_3

ws_run_block 4 'Verify' 'Verify' 120 123 'bash' '' <<'WS_TEST_BLOCK_600_4'
kubectl -n unicorn-store-spring rollout status deploy/unicorn-store-spring --timeout=300s

git -C ~/environment/unicorn-store-spring add -A \
  && git -C ~/environment/unicorn-store-spring commit -q -m "non-blocking publish"
WS_TEST_BLOCK_600_4

ws_skip_block 5 'Verify' 'Verify' 128 134 'text' '' 'copy action disabled'

ws_run_block 6 'Check against best practices' 'In the Shell terminal:' 157 157 'bash' 'non-interactive' <<'WS_TEST_BLOCK_600_6'
cd ~/environment && claude -c -p "How is unicorn-store-spring doing against best practices?"
WS_TEST_BLOCK_600_6

ws_skip_block 7 'Check against best practices' 'Check against best practices' 165 185 'text' '' 'copy action disabled'

ws_end_page

ws_begin_page 'Close the loop' 650 'close-the-loop/index.en.md'

ws_run_block 1 'Close the loop' 'In the Shell terminal:' 21 21 'bash' 'non-interactive' <<'WS_TEST_BLOCK_650_1'
cd ~/environment && claude -c -p "Right-size unicorn-store-spring again and fix item 10."
WS_TEST_BLOCK_650_1

ws_skip_block 2 'Close the loop' 'Claude re-runs sizeMemory and sizeCpu against the pod as it is now, and edits two files. It edits and stops.' 31 50 'text' '' 'copy action disabled'

ws_run_block 3 'Build and roll out' 'In the Shell terminal. The heap changed, so the build retakes the checkpoint:' 61 64 'bash' '' 1200 <<'WS_TEST_BLOCK_650_3'
# heap flags changed: rebuild the checkpoint (≈ 1 min, the JAR is cached)
~/environment/unicorn-store-spring/scripts/build.sh crac Dockerfile.crac

kubectl -n unicorn-store-spring apply -f ~/environment/unicorn-store-spring/k8s/deployment.yaml
WS_TEST_BLOCK_650_3

ws_run_block 4 'Verify' 'Verify' 79 87 'bash' '' <<'WS_TEST_BLOCK_650_4'
kubectl -n unicorn-store-spring rollout status deploy/unicorn-store-spring --timeout=300s

# heap flags from the new checkpoint: 75 % / 50 % of the new limit
kubectl -n unicorn-store-spring exec deploy/unicorn-store-spring -c unicorn-store-spring -- \
  sh -c 'JAVA_TOOL_OPTIONS= jcmd $(jcmd -l | grep -v JCmd | cut -d" " -f1) VM.flags' \
  | tr ' ' '\n' | grep -E 'MaxHeapSize|InitialHeapSize'

git -C ~/environment/unicorn-store-spring add -A \
  && git -C ~/environment/unicorn-store-spring commit -q -m "re-size after code fix, shutdown budget"
WS_TEST_BLOCK_650_4

ws_skip_block 5 'Verify' 'Verify' 92 98 'text' '' 'copy action disabled'

ws_run_block 6 'Check against best practices' 'In the Shell terminal:' 127 127 'bash' 'non-interactive' <<'WS_TEST_BLOCK_650_6'
cd ~/environment && claude -c -p "How is unicorn-store-spring doing against best practices?"
WS_TEST_BLOCK_650_6

ws_skip_block 7 'Check against best practices' 'Check against best practices' 135 150 'text' '' 'copy action disabled'

ws_skip_block 8 'Choosing for your own workloads' 'Choosing for your own workloads' 159 174 '' '' 'informational block without language'

ws_end_page

ws_finish_run
