pipeline:
  name: Dayforce Build and Deploy
  identifier: Dayforce_Build_and_Deploy
  projectIdentifier: soto_sandbox
  orgIdentifier: sandbox
  tags:
    owner: soto
  variables:
    - name: skip_build
      type: String
      description: Set to 'true' to skip the Build stage and only deploy
      required: false
      default: "false"
      value: <+input>.allowedValues(true,false)
  properties:
    ci:
      codebase:
        connectorRef: alexsotoharness
        repoName: java-on-aws
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: Build and test unicorn-store-spring with Test Intelligence
        type: CI
        when:
          pipelineStatus: Success
          condition: <+pipeline.variables.skip_build> != "true"
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            key: maven-cache-<+codebase.branch>
            paths:
              - /harness/.m2
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - stepGroup:
                  name: Secret Detection
                  identifier: Secret_Detection
                  steps:
                    - step:
                        type: Gitleaks
                        name: Secret Detection
                        identifier: Secret_Detection
                        spec:
                          mode: orchestration
                          config: default
                          target:
                            type: repository
                            detection: auto
                          advanced:
                            log:
                              level: info
              - stepGroup:
                  name: SCA Scans
                  identifier: SCA_Scans
                  steps:
                    - parallel:
                        - step:
                            type: Owasp
                            name: Owasp
                            identifier: Owasp
                            spec:
                              mode: orchestration
                              config: default
                              target:
                                type: repository
                                detection: auto
                              advanced:
                                log:
                                  level: info
                                args:
                                  cli: "-n"
                            failureStrategies:
                              - onFailure:
                                  errors:
                                    - AllErrors
                                  action:
                                    type: Ignore
                            when:
                              stageStatus: Success
                              condition: "false"
                        - step:
                            type: OsvScanner
                            name: OsvScanner
                            identifier: OsvScanner
                            spec:
                              mode: orchestration
                              config: default
                              target:
                                type: repository
                                detection: auto
                              advanced:
                                log:
                                  level: info
              - stepGroup:
                  name: SAST Scans
                  identifier: SAST_Scans
                  steps:
                    - step:
                        type: Semgrep
                        name: Semgrep
                        identifier: Semgrep
                        spec:
                          mode: orchestration
                          config: default
                          target:
                            type: repository
                            detection: auto
                          advanced:
                            log:
                              level: info
              - stepGroup:
                  name: Unit Tests
                  identifier: Unit_Tests
                  steps:
                    - parallel:
                        - step:
                            type: RunTests
                            name: Run Tests
                            identifier: Run_Tests_with_TI
                            spec:
                              connectorRef: account.harnessImage
                              image: maven:3.9-amazoncorretto-25
                              language: Java
                              buildTool: Maven
                              args: test -f apps/unicorn-store-spring/pom.xml -Dmaven.repo.local=/harness/.m2/repository
                              runOnlySelectedTests: true
                              preCommand: |
                                export MAVEN_OPTS="-Dmaven.repo.local=/harness/.m2/repository"
                              reports:
                                type: JUnit
                                spec:
                                  paths:
                                    - "**/target/surefire-reports/*.xml"
                              enableTestSplitting: false
                            when:
                              stageStatus: Success
                              condition: "false"
                          contextType: Pipeline
                        - step:
                            type: Test
                            name: Test Intelligence
                            identifier: Test_Intelligence
                            spec:
                              connectorRef: account.harnessImage
                              image: maven:3.9-amazoncorretto-25
                              shell: Sh
                              command: |
                                export MAVEN_OPTS="-Dmaven.repo.local=/harness/.m2/repository"
                                mvn test -f apps/unicorn-store-spring/pom.xml -Dmaven.repo.local=/harness/.m2/repository
                              reports:
                                type: JUnit
                                spec:
                                  paths:
                                    - "**/target/surefire-reports/*.xml"
                              intelligenceMode: true
              - step:
                  type: BuildAndPushECR
                  name: Build and Push to ECR
                  identifier: Build_and_Push_to_ECR
                  spec:
                    connectorRef: account.AWS
                    region: us-east-1
                    account: "759984737373"
                    imageName: unicorn-store-spring
                    tags:
                      - latest
                      - <+pipeline.sequenceId>
                    caching: true
                    dockerfile: apps/unicorn-store-spring/Dockerfile
                    context: apps/unicorn-store-spring
                contextType: Pipeline
              - stepGroup:
                  name: Container Scans
                  identifier: Container_Scans
                  steps:
                    - step:
                        type: AquaTrivy
                        name: AquaTrivy
                        identifier: AquaTrivy
                        spec:
                          mode: orchestration
                          config: default
                          target:
                            type: container
                            detection: auto
                          advanced:
                            log:
                              level: info
                          privileged: true
                          image:
                            region: us-east-1
                            type: aws_ecr
                            tag: latest
                            access_id: <+secrets.getValue("account.AWS_Access_Key")>
                            access_token: <+secrets.getValue("account.AWS_Secret_Access_Key")>
                            name: unicorn-store-spring
                            domain: 759984737373.dkr.ecr.us-east-1.amazonaws.com
                          sbom:
                            format: spdx-json
          sharedPaths:
            - /var/run
    - stage:
        name: EKS Dev Deploy
        identifier: EKS_Dev_Deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          environment:
            environmentRef: awsnonprod
            deployToAll: false
            infrastructureDefinitions:
              - identifier: eksparsonunicorndev
          execution:
            steps:
              - stepGroup:
                  name: Database Updates
                  identifier: Database_Updates
                  steps:
                    - step:
                        type: DBSchemaApply
                        name: Apply Schema
                        identifier: Apply_Schema
                        spec:
                          connectorRef: account.harnessImage
                          migrationType: Liquibase
                          dbSchema: unicornstoreschema
                          dbInstance: unicornstorepostgresdev
                        timeout: 10m
                  stepGroupInfra:
                    type: KubernetesDirect
                    spec:
                      connectorRef: eksparson
              - stepGroup:
                  name: Blue Green Deployment
                  identifier: Blue_Green_Deployment
                  steps:
                    - step:
                        type: K8sBlueGreenDeploy
                        name: Stage Deployment
                        identifier: Stage_Deployment
                        spec:
                          skipDryRun: false
                          pruningEnabled: false
                          skipUnchangedManifest: false
                        timeout: 10m
                      contextType: Pipeline
                    - step:
                        type: HarnessApproval
                        name: Approval
                        identifier: Approval
                        spec:
                          approvalMessage: Please review the following information and approve the pipeline progression
                          includePipelineExecutionHistory: true
                          isAutoRejectEnabled: false
                          approvers:
                            userGroups:
                              - account._account_all_users
                            minimumCount: 1
                            disallowPipelineExecutor: false
                          approverInputs: []
                        timeout: 1d
                    - step:
                        type: K8sBGSwapServices
                        name: Swap Stage and Primary
                        identifier: Swap_Stage_and_Primary
                        spec: {}
                        timeout: 10m
              - stepGroup:
                  name: Primary Deployment
                  identifier: Primary_Deployment
                  steps:
                    - step:
                        name: Rollout Deployment
                        identifier: rolloutDeployment
                        type: K8sRollingDeploy
                        timeout: 10m
                        spec:
                          skipDryRun: false
                          pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
          service:
            serviceRef: <+input>.default("unicorn_store_spring")
            serviceInputs: <+input>
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - stage:
        name: EKS Prod Deploy
        identifier: EKS_Prod_Deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          environment:
            environmentRef: awsprod
            deployToAll: false
            infrastructureDefinitions:
              - identifier: eksparsonunicornprod
          execution:
            steps:
              - stepGroup:
                  name: Canary Deployment
                  identifier: Canary_Deployment
                  steps:
                    - step:
                        type: K8sCanaryDeploy
                        name: Canary Deploy
                        identifier: Canary_Deploy
                        spec:
                          skipDryRun: false
                          instanceSelection:
                            spec:
                              percentage: 10
                            type: Percentage
                        timeout: 10m
                    - step:
                        type: HarnessApproval
                        name: Approval
                        identifier: Approval
                        spec:
                          approvalMessage: Please review the following information and approve the pipeline progression
                          includePipelineExecutionHistory: true
                          isAutoRejectEnabled: false
                          approvers:
                            userGroups:
                              - account._account_all_users
                            minimumCount: 1
                            disallowPipelineExecutor: false
                          approverInputs: []
                        timeout: 1d
                      contextType: Pipeline
                    - step:
                        type: K8sCanaryDelete
                        name: Canary Delete
                        identifier: Canary_Delete
                        spec: {}
                        timeout: 10m
              - stepGroup:
                  name: Primary Deployment
                  identifier: Primary_Deployment
                  steps:
                    - step:
                        type: K8sRollingDeploy
                        name: Rollout Deployment
                        identifier: Rollout_Deployment
                        spec:
                          skipDryRun: false
                          pruningEnabled: false
                        timeout: 10m
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
          service:
            useFromStage:
              stage: EKS_Dev_Deploy
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        when:
          pipelineStatus: Success
  allowStageExecutions: true
