pipeline:
  name: Dayforce Build and Deploy
  identifier: Dayforce_Build_and_Deploy
  projectIdentifier: soto_sandbox
  orgIdentifier: sandbox
  tags:
    owner: soto
  variables:
    - name: skip_build
      type: String
      description: Set to 'true' to skip the Build stage and only deploy
      required: false
      default: "false"
      value: <+input>.allowedValues(true,false)
  properties:
    ci:
      codebase:
        connectorRef: alexsotoharness
        repoName: java-on-aws
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: Build and test unicorn-store-jakarta with Test Intelligence
        type: CI
        when:
          pipelineStatus: Success
          condition: <+pipeline.variables.skip_build> != "true"
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            key: maven-cache-<+codebase.branch>
            paths:
              - /harness/.m2
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - parallel:
                  - step:
                      type: RunTests
                      name: Run Tests
                      identifier: Run_Tests_with_TI
                      spec:
                        connectorRef: account.harnessImage
                        image: maven:3.9.9-amazoncorretto-21
                        language: Java
                        buildTool: Maven
                        args: test -f apps/unicorn-store-jakarta/pom.xml -Dmaven.repo.local=/harness/.m2/repository
                        runOnlySelectedTests: true
                        preCommand: |
                          export MAVEN_OPTS="-Dmaven.repo.local=/harness/.m2/repository"
                        reports:
                          type: JUnit
                          spec:
                            paths:
                              - "**/target/surefire-reports/*.xml"
                        enableTestSplitting: false
                  - step:
                      type: Test
                      name: Test Intelligence
                      identifier: Test_Intelligence
                      spec:
                        connectorRef: account.harnessImage
                        image: maven:3.9.9-amazoncorretto-21
                        shell: Sh
                        command: |
                          export MAVEN_OPTS="-Dmaven.repo.local=/harness/.m2/repository"
                          mvn test -f apps/unicorn-store-jakarta/pom.xml -Dmaven.repo.local=/harness/.m2/repository
                        reports:
                          type: JUnit
                          spec:
                            paths:
                              - "**/target/surefire-reports/*.xml"
                        intelligenceMode: true
              - step:
                  type: Run
                  name: Build WAR
                  identifier: Build_WAR
                  spec:
                    connectorRef: account.harnessImage
                    image: maven:3.9.9-amazoncorretto-21
                    shell: Sh
                    command: |
                      cd apps/unicorn-store-jakarta
                      mvn clean package -DskipTests -Dmaven.repo.local=/harness/.m2/repository
                      ls -la target/
              - parallel:
                  - step:
                      type: BuildAndPushDockerRegistry
                      name: Build and Push to DockerHub
                      identifier: Build_and_Push_to_DockerHub
                      spec:
                        connectorRef: dockerhubalexsotoharness
                        repo: alexsotoharness/unicorn-store-jakarta
                        tags:
                          - <+pipeline.sequenceId>
                          - latest
                        caching: true
                        dockerfile: apps/unicorn-store-jakarta/wildfly/Dockerfile
                        context: apps/unicorn-store-jakarta
                  - step:
                      type: BuildAndPushECR
                      name: Build and Push to ECR
                      identifier: Build_and_Push_to_ECR
                      spec:
                        connectorRef: account.AWS
                        region: us-east-1
                        account: <placeholder>
                        imageName: <placeholder>
                        tags:
                          - latest
                          - <+pipeline.sequenceId>
                        caching: true
                        dockerfile: <placeholder>
                        context: <placeholder>
    - stage:
        name: Database DevOps
        identifier: Database_DevOps
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - stepGroup:
                  name: Deploy DB Changes
                  identifier: Deploy_DB_Changes
                  steps:
                    - step:
                        type: DBSchemaApply
                        name: Apply Schema
                        identifier: Apply_Schema
                        spec:
                          connectorRef: account.harnessImage
                          migrationType: Liquibase
                          dbSchema: unicornstoreschema
                          dbInstance: unicornstorepostgresdev
                        timeout: 10m
                  stepGroupInfra:
                    type: KubernetesDirect
                    spec:
                      connectorRef: eksparson
                      namespace: unicorn-dev
            rollbackSteps: []
          serviceDependencies: []
        tags: {}
    - stage:
        name: Local Deploy
        identifier: Deploy_to_OrbStack
        description: Deploy unicorn-store-jakarta to local OrbStack Kubernetes cluster
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: unicorn_store_jakarta
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: dockerhub_image
                      sources:
                        - identifier: dockerhub_image
                          type: DockerRegistry
                          spec:
                            tag: <+input>.default(latest)
          environment:
            environmentRef: harnessdevenv
            deployToAll: false
            infrastructureDefinitions:
              - identifier: orbstack_local
          execution:
            steps:
              - step:
                  type: K8sRollingDeploy
                  name: Rolling Deployment
                  identifier: Rolling_Deployment
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
                  timeout: 10m
            rollbackSteps:
              - step:
                  type: K8sRollingRollback
                  name: Rollback
                  identifier: Rollback
                  spec:
                    pruningEnabled: false
                  timeout: 10m
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        when:
          pipelineStatus: Success
          condition: "false"
    - parallel:
        - stage:
            name: EKS Dev Deploy
            identifier: EKS_Dev_Deploy
            description: ""
            type: Deployment
            spec:
              deploymentType: Kubernetes
              environment:
                environmentRef: awsnonprod
                deployToAll: false
                infrastructureDefinitions:
                  - identifier: eksparsonunicorndev
              execution:
                steps:
                  - step:
                      type: K8sCanaryDeploy
                      name: Canary Deployment
                      identifier: Canary_Deployment
                      spec:
                        skipDryRun: false
                        instanceSelection:
                          spec:
                            percentage: 10
                          type: Percentage
                      timeout: 10m
                  - step:
                      type: HarnessApproval
                      name: Approval
                      identifier: Approval
                      spec:
                        approvalMessage: Please review the following information and approve the pipeline progression
                        includePipelineExecutionHistory: true
                        isAutoRejectEnabled: false
                        approvers:
                          userGroups:
                            - account._account_all_users
                          minimumCount: 1
                          disallowPipelineExecutor: false
                        approverInputs: []
                      timeout: 1d
                  - step:
                      type: K8sCanaryDelete
                      name: Delete Canary
                      identifier: Delete_Canary
                      spec: {}
                      timeout: 10m
                  - step:
                      name: Rollout Deployment
                      identifier: rolloutDeployment
                      type: K8sRollingDeploy
                      timeout: 10m
                      spec:
                        skipDryRun: false
                        pruningEnabled: false
                rollbackSteps:
                  - step:
                      name: Rollback Rollout Deployment
                      identifier: rollbackRolloutDeployment
                      type: K8sRollingRollback
                      timeout: 10m
                      spec:
                        pruningEnabled: false
              service:
                serviceRef: unicorn_store_jakarta
                serviceInputs:
                  serviceDefinition:
                    type: Kubernetes
                    spec:
                      artifacts:
                        primary:
                          primaryArtifactRef: dockerhub_image
                          sources:
                            - identifier: dockerhub_image
                              type: DockerRegistry
                              spec:
                                tag: <+input>.default(latest)
            tags: {}
            failureStrategies:
              - onFailure:
                  errors:
                    - AllErrors
                  action:
                    type: StageRollback
        - stage:
            name: EKS Prod Deploy
            identifier: EKS_Prod_Deploy
            description: ""
            type: Deployment
            spec:
              deploymentType: Kubernetes
              service:
                useFromStage:
                  stage: Deploy_to_OrbStack
              environment:
                environmentRef: awsprod
                deployToAll: false
                infrastructureDefinitions:
                  - identifier: eksparsonunicornprod
              execution:
                steps:
                  - step:
                      type: K8sBlueGreenDeploy
                      name: Blue Green Deploy
                      identifier: Blue_Green_Deploy
                      spec:
                        skipDryRun: false
                        pruningEnabled: false
                        skipUnchangedManifest: false
                      timeout: 10m
                  - step:
                      type: HarnessApproval
                      name: Approval
                      identifier: Approval
                      spec:
                        approvalMessage: Please review the following information and approve the pipeline progression
                        includePipelineExecutionHistory: true
                        isAutoRejectEnabled: false
                        approvers:
                          userGroups:
                            - account._account_all_users
                          minimumCount: 1
                          disallowPipelineExecutor: false
                        approverInputs: []
                      timeout: 1d
                  - step:
                      type: K8sBGSwapServices
                      name: Swap Primary and Stage
                      identifier: Swap_Primary_and_Stage
                      spec: {}
                      timeout: 10m
                rollbackSteps:
                  - step:
                      name: Rollback Rollout Deployment
                      identifier: rollbackRolloutDeployment
                      type: K8sRollingRollback
                      timeout: 10m
                      spec:
                        pruningEnabled: false
            tags: {}
            failureStrategies:
              - onFailure:
                  errors:
                    - AllErrors
                  action:
                    type: StageRollback
            when:
              pipelineStatus: Success
              condition: "false"
  allowStageExecutions: true
